### PR TITLE
Fix ParametricEQ showing wrong tooltip values

### PR DESCRIPTION
**Pull request by ustk**

### CODE REVIEW

**Review by ustk — COMMENTED** [review]
POSSIBLE BREAK OF OLD PROJECTS

**Review by christophhart — COMMENTED** [review]
What's the rationale behind removing this?

**Review by christophhart — CHANGES_REQUESTED** [review]
I'm afraid the getMidiNoteName change will break too many projects. I'd rather suggest you add another function that will forward all parameters of the underlying juce function:

https://docs.juce.com/master/classMidiMessage.html#aff9cacd221a092d203249a2c7435d9dc

```
Engine.getMidiNoteNameFormatted(int noteNumber, rest of juce args...)
```

**Comment by ustk** [comment]
> What's the rationale behind removing the custom laf for the MidiSource Panel?

The Midi Source Panel was showing custom LAFs buttons instead of tick boxes, deleting it might be a wrong move though...

**Comment by ustk** [comment]
> I'm afraid the getMidiNoteName change will break too many projects. I'd rather suggest you add another function that will forward all parameters of the underlying juce function:
> 
> https://docs.juce.com/master/classMidiMessage.html#aff9cacd221a092d203249a2c7435d9dc
> 
> ```
> Engine.getMidiNoteNameFormatted(int noteNumber, rest of juce args...)
> ```

Yeah, that's what I thought... I'll either write another one or just delete it then ;)

**Review by christophhart — APPROVED** [review]

**Pull request merged**
