### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by realnotsteve**

### CODE REVIEW

**Comment by davidhealey** [comment]
This PR contains a lot of commits over a long period of time. I think you should break this into individual PRs (use git cherry-pick). Each PR should include just the changes you have made. This makes it much easier for Christoph to look through the changes and approve them.

You can check out some of the other open PRs for examples.

**Comment by realnotsteve** [comment]
I've clearly never used GIT, and don’t know what I’m doing. I was trying to upload to two single files as separate pulls, and somehow that became one pull with 180, lol. Sorry, guys. Please delete the requests.

**Comment by davidhealey** [comment]
> I've clearly never used GIT, and don’t know what I’m doing. I was trying to upload to two single files as separate pulls, and somehow that became one pull with 180, lol. Sorry, guys. Please delete the requests.

Hi Bill, 

I'll try and get around to posting a video soon that shows how to create a pull request with just your changes.

The basic steps are:
Find the hash of the commit you want to create a pull request for. `git log`
Checkout a new branch, based on the latest develop branch from Christoph. `git checkout develop` then `git checkout -b my-feature-branch`
Add your commit to this new branch `git cherry-pick your-commit-hash`
Push the new branch to github `git push --set-upstream origin my-feature-branch`

Then go to github and you should see a notification about your new branch, and by clicking it you can create a pull request.

**Comment by realnotsteve** [comment]
Awesome, thank you.

**Pull request merged**
