### PR TITLE
Added getProjectInfo function

### PR DESCRIPTION
**Pull request by davidhealey**

### CODE REVIEW

**Review by christoph-hart — COMMENTED** [review]
Does this work in a compiled plugin? I think you need eg. `FrontendHandler::getProjectName()` instead of querying the HiseSettings (which fetches the information from the project_info.xml in the project folder).

**Comment by davidhealey** [comment]
Oh you could be right, I didn't check in a compiled plugin. I'll test it now.

**Comment by davidhealey** [comment]
Yeah you're correct, it just shows generic data in the compiled project. I'll make fixes and update this pull request.

**Comment by christoph-hart** [comment]
The methods are listed here:

https://github.com/christophhart/HISE/blob/73e0e299493ce9236e6fafa7938d3477fcc36a4a/hi_core/hi_core/PresetHandler.h#L374

They are static methods (which are defined in the autogenerated Plugin.cpp file in the Binaries subfolder, so you can call them like this:

```
auto version = hise::FrontentHandler::getProjectVersion();
```

In order to distinguish between HISE and compiled code, use the `USE_BACKEND` macro:


```
#if USE_BACKEND
// Your stuff here
#else
// New stuff here
#endif

**Pull request merged**
