### PR TITLE
Changed hashing algorithm to MD5 because it's faster - or so I've bee…

### PR DESCRIPTION
**Pull request by davidhealey**
…n lead to believe.

### CODE REVIEW

**Comment by christoph-hart** [comment]
I'm not sure this is relevant (plus it breaks old code).

The MD5 algorithm is faster, however I think that the bottleneck here is reading each byte of the file, which takes ages with big sample files.

**Comment by davidhealey** [comment]
Do you have a suggestion for verifying the integrity of downloaded zips with HISE?

**Comment by christoph-hart** [comment]
I think we resorted to just the file size with Dorian Marko Piano.

**Comment by davidhealey** [comment]
Hmm, so simple but I think that probably is the way to go.

**Pull request closed without merging**
